default['couchbase']['node1']['ipaddress'] = "33.33.33.101"
default['couchbase']['node2']['ipaddress'] = "33.33.33.102"
default['couchbase']['server']['username'] = "Administrator"
default['couchbase']['server']['password'] = "hello123@"
default['couchbase']['server']['repo_package_url'] = "http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-x86_64.rpm"
default['couchbase']['server']['repo_package_file'] = "couchbase-release-1.0-2-x86_64.rpm"
